# Generated by Django 5.2.7 on 2025-10-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_documentupload_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='extracted_text_preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
