# Generated by Django 5.2.7 on 2025-10-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_documentupload_google_drive_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='group',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='file',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='google_drive_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UploadGroup',
        ),
    ]
