# Generated by Django 5.2.7 on 2025-11-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_documentupload_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='extracted_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
